title: Leticia Moreira
logo: /assets/img/profile.webp
description: 
show_downloads: true
google_analytics: G-9TE7BFHH2M
theme: jekyll-theme-minimal

urls:
  profile: https://github.com/fkdarven
  linkedin: https://www.linkedin.com/in/letícia-moreira-566997177/
  whatsapp: https://whatsa.me/5549991467284

